// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRM.DataAccess.Context;
#nullable disable

namespace PRM.DataAccess.Migrations
{
    [DbContext(typeof(PrmDbContext))]
    [Migration("20260528143238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            modelBuilder.Entity("PRM.Models.Entities.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");
                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");
                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");
                    b.Property<int>("UtilisationPercent")
                        .HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId");
                    b.HasIndex("ProjectId");
                    b.ToTable("Allocations", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");
                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<int>("UserId")
                        .HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("UserId")
                        .IsUnique();
                    b.ToTable("Employees", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.EmployeeSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");
                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<int>("SkillId")
                        .HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("SkillId");
                    b.HasIndex("EmployeeId", "SkillId")
                        .IsUnique();
                    b.ToTable("EmployeeSkills", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");
                    b.Property<int>("SortOrder")
                        .HasColumnType("int");
                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("Milestones", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<int>("ManagerId")
                        .HasColumnType("int");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.HasKey("Id");
                    b.HasIndex("ManagerId");
                    b.ToTable("Projects", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("Name")
                        .IsUnique();
                    b.ToTable("Skills", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("LlmApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<int>("MaxWeeklyHours")
                        .HasColumnType("int");
                    b.Property<int>("SchedulerIntervalHours")
                        .HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("SystemConfigs", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");
                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<int>("TotalHours")
                        .HasColumnType("int");
                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId", "WeekStartDate")
                        .IsUnique();
                    b.ToTable("Timesheets", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.TimesheetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ActivityTags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<decimal>("Hours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");
                    b.Property<int>("TimesheetId")
                        .HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.HasIndex("TimesheetId");
                    b.ToTable("TimesheetEntries", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("bit");
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");
                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("Email")
                        .IsUnique();
                    b.HasIndex("Username")
                        .IsUnique();
                    b.ToTable("Users", (string)null);
                });
            modelBuilder.Entity("PRM.Models.Entities.Allocation", b =>
                {
                    b.HasOne("PRM.Models.Entities.Employee", "Employee")
                        .WithMany("Allocations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("PRM.Models.Entities.Project", "Project")
                        .WithMany("Allocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Employee");
                    b.Navigation("Project");
                });
            modelBuilder.Entity("PRM.Models.Entities.Employee", b =>
                {
                    b.HasOne("PRM.Models.Entities.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("PRM.Models.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("PRM.Models.Entities.EmployeeSkill", b =>
                {
                    b.HasOne("PRM.Models.Entities.Employee", "Employee")
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("PRM.Models.Entities.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Employee");
                    b.Navigation("Skill");
                });
            modelBuilder.Entity("PRM.Models.Entities.Milestone", b =>
                {
                    b.HasOne("PRM.Models.Entities.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Project");
                });
            modelBuilder.Entity("PRM.Models.Entities.Project", b =>
                {
                    b.HasOne("PRM.Models.Entities.User", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Manager");
                });
            modelBuilder.Entity("PRM.Models.Entities.Timesheet", b =>
                {
                    b.HasOne("PRM.Models.Entities.Employee", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Employee");
                });
            modelBuilder.Entity("PRM.Models.Entities.TimesheetEntry", b =>
                {
                    b.HasOne("PRM.Models.Entities.Project", "Project")
                        .WithMany("TimesheetEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("PRM.Models.Entities.Timesheet", "Timesheet")
                        .WithMany("Entries")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Project");
                    b.Navigation("Timesheet");
                });
            modelBuilder.Entity("PRM.Models.Entities.Employee", b =>
                {
                    b.Navigation("Allocations");
                    b.Navigation("Skills");
                    b.Navigation("Timesheets");
                });
            modelBuilder.Entity("PRM.Models.Entities.Project", b =>
                {
                    b.Navigation("Allocations");
                    b.Navigation("Milestones");
                    b.Navigation("TimesheetEntries");
                });
            modelBuilder.Entity("PRM.Models.Entities.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");
                });
            modelBuilder.Entity("PRM.Models.Entities.Timesheet", b =>
                {
                    b.Navigation("Entries");
                });
            modelBuilder.Entity("PRM.Models.Entities.User", b =>
                {
                    b.Navigation("Employee");
                    b.Navigation("ManagedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
